source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'SwiftImport_Tests', :exclusive => true do
   pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git'
   pod 'MagicalRecord'
end
